### ISSUE TITLE
0.3.1 throws a lot of errors and doesn't work

### ISSUE THREAD

**Issue by codepreneur** [terrawheat/ember-cli-keyboard-actions#2]
I have just upgraded to 0.3.1 and am getting these errors (Mac OS X 10.10.3 Latest Chrome):

![image](https://cloud.githubusercontent.com/assets/3421858/7956217/61d08c70-09d6-11e5-81c8-9fe6abf55324.png)

when I type into this input

```
{{input class="input__text u-1/1 has-icon" type="text" placeholder="Type to search participants" value=searchTerm enter="query" key-press="whenKeyIsPressed"}}
```

or this

```
{{input class="input__text u-1/1 has-icon" type="text" placeholder="Type to search participants" value=searchTerm}}
```

Here are my Ember versions:

```
DEBUG: -------------------------------
DEBUG: Ember           : 1.12.0
DEBUG: Ember Data      : 1.0.0-beta.18
DEBUG: jQuery          : 1.11.3
DEBUG: Model Fragments : 0.3.2
DEBUG: -------------------------------
```

and...

```
ember -v --verbose

version: 0.2.5

http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
npm: 2.10.0

```

**Comment by isolationism** [comment]
I'm seeing the same thing here with 0.3.1.

**Comment by terrawheat** [comment]
I struggled to replicate this, I think it's something to do with nested views and chord states. I've wrapped this safely and cut a 0.3.2 - can you guys let me know if it carries on being a problem?

@isolationism @codepreneur
